Python 3 does not have a tp_print member in PyTypeObject
This avoids an int-conversion compiler error with current
compilers:

./kdumpfile.c:1449:9: error: initialization of 'long int' from 'int (*)(PyObject *, FILE *, int)' {aka 'int (*)(struct _object *, FILE *, int)'} makes integer from pointer without a cast
 1449 |         attr_dir_print,                 /* tp_print*/
      |         ^~~~~~~~~~~~~~


In Python 3.11, the field at this position is called tp_vectorcall_offset
and has type Py_ssize_t, hence the error.