addrxlat: added missing cb_read_caps copy in Context object
Encounter the following error with libkdumpfile gdbserver:

> AttributeError: 'Context' object has no attribute 'cb_read_caps'. Did you mean: 'next_read_caps'?

my code was calling system.os_init as:

> ctx = self.kdump.get_addrxlat_ctx()
> ...
> system.os_init(ctx=ctx, arch=self.arch, os_type="linux", rootpgt=fulladdr)

In gdb session I found that code reached cb_read_caps C function
and it did PyObject_CallMethod for "cb_read_caps":

> cb_read_caps(const addrxlat_cb_t *cb)
> {
> ..
>	result = PyObject_CallMethod((PyObject*)self, "cb_read_caps", NULL);

It looks like cb_read_caps attribute was not being copied in ctx_new as
in the case of other attributes. Added copying cb_read_caps similar to
all the other attributes. It resolved my issue.

Signed-off-by: Alexander Kamensky <alexander.kamensky42@gmail.com>