python: Fix kdumpfile.__init__ in python3
With crash-python (and components libkdumpfile and gdb-python) using python3,
we run into:
...
crash-python initializing...
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "crash-python/lib/crash/session.py", \
      line 45, in __init__
    self.kernel.attach_vmcore(vmcore, debug)
  File "crash-python/lib/crash/kernel.py", \
      line 112, in attach_vmcore
    self.vmcore = kdumpfile(vmcore_filename)
  File "libkdumpfile/lib/python3.6/site-packages/kdumpfile/__init__.py", \
      line 9, in __init__
    super(kdumpfile, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes no parameters
...

The kdumpfile class declared in kdumpfile/__init__.py confusingly has a
base class with the same name, which refers to kdumpfile_object_type in
kdumpfile.c, which has a NULL tp_init and NULL tp_base.
The __init__ method of the first calls "super(kdumpfile, self).__init__".
In python2 (given the NULL tp_init and NULL tp_base), no code is executed.
In python3, all classes are new-style classes (which means implicitly having
the class object as root class), so object.__init__ ends up being called.
And since:
- the class instantiation of kdumpfile takes an argument,
- the argument is handled in the baseclass tp_new, but
  not in the baseclass tp_init (given that it's NULL)
the argument is passed on to object.__init__ which then raises an exception
"TypeError: object.__init__() takes no parameters".

Fix this by removing the super().__init__ call.

[ An alternative solution could be to to implement tp_init in the baseclass
and drop the argument there. ]