python/addrxlat: Fix superclass __init__ invocation
This fixes a problem with __init__() invocation. Even though some
base classes in _addrxlat accept a parameter, they only override
__new__ (via tp_new slot), they never override __init__. This is by
design, so that the C code stays at a minimum.

The classes in the addrxlat module provide some more syntactic sugar
and override __init__, but not __new__(). Nevertheless, in these
classes both __new__() and __init__() are overridden from base object
type.

Now, object.__init__() ignores any extra arguments if either (but not
both) __init__ or __new__() is overridden. Consequently, the _addrxlat
classes can be instantiated with no problem, but addrxlat clasess
fail with:

TypeError: object.__init__() takes no parameters

Signed-off-by: Petr Tesarik <ptesarik@suse.com>